---
resources:
- name: newman-repo
  type: git
  source:
    uri: https://github.com/Suriyams3/postman-automation-service.git
  
jobs:
- name: test-rest-api
  public: true
  plan:
  - get: newman-repo
  - task: test-api
    file: newman-repo/src/newman-task.yml
    params: { "ENVIRONMENT_URL": "https://github.com/Suriyams3/postman-automation-service/blob/main/src/BookDevEnvironment.json", "COLLECTION_URL": "https://github.com/Suriyams3/postman-automation-service/blob/main/src/bookApiCollectionwoAuth.json" }